apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: conspiracy-site
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: conspiracy-nginx
    spec:
      containers:
      - name: conspiracy-nginx
        image: gcr.io/onyx-parser-132016/conspiracy-site:v1
        ports:
        - containerPort: 80